DROP SCHEMA IF EXISTS hockey_schema;

CREATE SCHEMA hockey_schema;
USE hockey_schema;

CREATE TABLE team (
    team_code VARCHAR(3) NOT NULL,
    team_name VARCHAR(100),
    PRIMARY KEY (team_code)
);

CREATE TABLE season (
    season_year INT,
    season_label VARCHAR(20),
    num_games INT,
    PRIMARY KEY (season_year)
);

CREATE TABLE player (
    player_id INT,
    player_name VARCHAR(100),
    position VARCHAR(2),
    shoots VARCHAR(1),
    birth_date DATE,
    weight INT,
    height VARCHAR(10),
    nationality VARCHAR(3),
    jersey_number INT,
    current_team VARCHAR(3),
    PRIMARY KEY (player_id),
    FOREIGN KEY (current_team) REFERENCES team(team_code)
);

CREATE TABLE game (
    game_id INT,
    season_year INT,
    date DATE,
    home_team VARCHAR(3),
    away_team VARCHAR(3),
    home_score INT,
    away_score INT,
    home_win BOOLEAN AS (home_score > away_score) STORED,
    is_playoffs BOOLEAN,
    PRIMARY KEY (game_id),
    FOREIGN KEY (season_year) REFERENCES season(season_year),
    FOREIGN KEY (home_team) REFERENCES team(team_code),
    FOREIGN KEY (away_team) REFERENCES team(team_code)
);

CREATE TABLE player_game_stats (
    player_id INT,
    game_id INT,
    situation VARCHAR(10),
    icetime INT,
    shifts INT,
    game_score FLOAT,
    goals INT,
    primary_assists INT,
    secondary_assists INT,
    points INT AS (goals + primary_assists + secondary_assists) STORED,
    shots_on_goal INT,
    missed_shots INT,
    blocked_shot_attempts INT,
    shot_attempts INT AS (shots_on_goal + missed_shots + blocked_shot_attempts) STORED,
    x_goals FLOAT,
    rebounds INT,
    rebound_goals INT,
    rebound_x_goals FLOAT,
    x_goals_from_x_rebounds FLOAT,
    x_goals_from_actual_rebounds FLOAT,
    high_danger_shots INT,
    medium_danger_shots INT,
    low_danger_shots INT,
    high_danger_x_goals FLOAT,
    medium_danger_x_goals FLOAT,
    low_danger_x_goals FLOAT,
    high_danger_goals INT,
    medium_danger_goals INT,
    low_danger_goals INT,
    flurry_adjusted_x_goals FLOAT,
    score_venue_adjusted_x_goals FLOAT,
    hits INT,
    takeaways INT,
    giveaways INT,
    d_zone_giveaways INT,
    face_offs_won INT,
    penalties INT,
    penalty_minutes INT,
    o_zone_shift_starts INT,
    d_zone_shift_starts INT,
    neutral_zone_shift_starts INT,
    fly_shift_starts INT,
    shots_blocked_by_player INT,
    on_ice_f_goals INT,
    on_ice_f_x_goals FLOAT,
    on_ice_f_shot_attempts INT,
    on_ice_f_high_danger_shots INT,
    on_ice_f_high_danger_goals INT,
    on_ice_f_high_danger_x_goals FLOAT,
    on_ice_a_goals INT,
    on_ice_a_x_goals FLOAT,
    on_ice_a_shot_attempts INT,
    on_ice_a_high_danger_shots INT,
    on_ice_a_high_danger_goals INT,
    on_ice_a_high_danger_x_goals FLOAT,
    x_goals_for_after_shifts FLOAT,
    x_goals_against_after_shifts FLOAT,
    PRIMARY KEY (player_id, game_id, situation),
    CONSTRAINT chk_player_situation CHECK (situation IN ('all','5on5','5on4','4on5','other')),
    FOREIGN KEY (player_id) REFERENCES player(player_id),
    FOREIGN KEY (game_id) REFERENCES game(game_id)
);

CREATE TABLE goalie_game_stats (
    player_id INT,
    game_id INT,
    situation VARCHAR(10),
    icetime INT,
    x_goals FLOAT,
    goals_against INT,
    unblocked_shot_attempts INT,
    x_rebounds FLOAT,
    rebounds INT,
    x_freeze FLOAT,
    freeze INT,
    x_on_goal FLOAT,
    on_goal INT,
    x_play_stopped FLOAT,
    play_stopped INT,
    x_play_continued_in_zone FLOAT,
    play_continued_in_zone INT,
    x_play_continued_outside_zone FLOAT,
    play_continued_outside_zone INT,
    flurry_adjusted_x_goals FLOAT,
    low_danger_shots INT,
    medium_danger_shots INT,
    high_danger_shots INT,
    low_danger_x_goals FLOAT,
    medium_danger_x_goals FLOAT,
    high_danger_x_goals FLOAT,
    low_danger_goals INT,
    medium_danger_goals INT,
    high_danger_goals INT,
    blocked_shot_attempts INT,
    penalty_minutes INT,
    penalties INT,
    PRIMARY KEY (player_id, game_id, situation),
    CONSTRAINT chk_goalie_situation CHECK (situation IN ('all','5on5','5on4','4on5','other')),
    FOREIGN KEY (player_id) REFERENCES player(player_id),
    FOREIGN KEY (game_id) REFERENCES game(game_id)
);

CREATE TABLE line (
    line_id VARCHAR(25),
    line_name VARCHAR(150),
    position VARCHAR(10),
    team_code VARCHAR(3),
    PRIMARY KEY (line_id),
    FOREIGN KEY (team_code) REFERENCES team(team_code)
);

CREATE TABLE line_player (
    line_id VARCHAR(25),
    player_id INT,
    season_year INT,
    PRIMARY KEY (line_id, player_id, season_year),
    FOREIGN KEY (line_id) REFERENCES line(line_id),
    FOREIGN KEY (player_id) REFERENCES player(player_id),
    FOREIGN KEY (season_year) REFERENCES season(season_year)
);

CREATE TABLE line_game_stats (
    line_id VARCHAR(25),
    game_id INT,
    situation VARCHAR(10),
    icetime INT,
    goals_for INT,
    x_goals_for FLOAT,
    x_on_goal_for FLOAT,
    shots_on_goal_for INT,
    missed_shots_for INT,
    blocked_shot_attempts_for INT,
    shot_attempts_for INT,
    rebounds_for INT,
    rebound_goals_for INT,
    rebound_x_goals_for FLOAT,
    x_goals_from_x_rebounds_for FLOAT,
    x_goals_from_actual_rebounds_for FLOAT,
    high_danger_shots_for INT,
    medium_danger_shots_for INT,
    low_danger_shots_for INT,
    high_danger_x_goals_for FLOAT,
    medium_danger_x_goals_for FLOAT,
    low_danger_x_goals_for FLOAT,
    high_danger_goals_for INT,
    medium_danger_goals_for INT,
    low_danger_goals_for INT,
    flurry_adjusted_x_goals_for FLOAT,
    score_venue_adjusted_x_goals_for FLOAT,
    total_shot_credit_for FLOAT,
    hits_for INT,
    takeaways_for INT,
    giveaways_for INT,
    d_zone_giveaways_for INT,
    face_offs_won_for INT,
    penalties_for INT,
    penalty_minutes_for INT,
    goals_against INT,
    x_goals_against FLOAT,
    x_on_goal_against FLOAT,
    shots_on_goal_against INT,
    missed_shots_against INT,
    blocked_shot_attempts_against INT,
    shot_attempts_against INT,
    rebounds_against INT,
    rebound_goals_against INT,
    rebound_x_goals_against FLOAT,
    x_goals_from_x_rebounds_against FLOAT,
    x_goals_from_actual_rebounds_against FLOAT,
    high_danger_shots_against INT,
    medium_danger_shots_against INT,
    low_danger_shots_against INT,
    high_danger_x_goals_against FLOAT,
    medium_danger_x_goals_against FLOAT,
    low_danger_x_goals_against FLOAT,
    high_danger_goals_against INT,
    medium_danger_goals_against INT,
    low_danger_goals_against INT,
    flurry_adjusted_x_goals_against FLOAT,
    score_venue_adjusted_x_goals_against FLOAT,
    total_shot_credit_against FLOAT,
    hits_against INT,
    takeaways_against INT,
    giveaways_against INT,
    d_zone_giveaways_against INT,
    face_offs_won_against INT,
    penalties_against INT,
    penalty_minutes_against INT,
    PRIMARY KEY (line_id, game_id, situation),
    CONSTRAINT chk_line_situation CHECK (situation IN ('all','5on5','5on4','4on5','other')),
    FOREIGN KEY (line_id) REFERENCES line(line_id),
    FOREIGN KEY (game_id) REFERENCES game(game_id)
);

CREATE TABLE shot (
    shot_id INT AUTO_INCREMENT,
    game_id INT NOT NULL,
    team_code VARCHAR(3) NOT NULL,
    shooter_player_id INT,
    goalie_id INT,
    event VARCHAR(10),
    shot_type VARCHAR(20),
    shot_on_empty_net BOOLEAN,
    shot_rebound BOOLEAN,
    shot_rush BOOLEAN,
    shot_generated_rebound BOOLEAN,
    shot_goalie_froze BOOLEAN,
    shot_play_stopped BOOLEAN,
    shot_play_continued_in_zone BOOLEAN,
    shot_play_continued_outside_zone BOOLEAN,
    x_cord_adjusted FLOAT,
    y_cord_adjusted FLOAT,
    arena_adjusted_x_cord FLOAT,
    arena_adjusted_y_cord FLOAT,
    shot_angle_adjusted FLOAT,
    arena_adjusted_shot_distance FLOAT,
    x_goal FLOAT,
    x_rebound FLOAT,
    x_freeze FLOAT,
    shot_angle_plus_rebound FLOAT,
    shot_angle_rebound_royal_road BOOLEAN,
    period INT,
    time INT,
    home_team_goals INT,
    away_team_goals INT,
    home_empty_net BOOLEAN,
    away_empty_net BOOLEAN,
    home_skaters_on_ice INT,
    away_skaters_on_ice INT,
    last_event_category VARCHAR(30),
    last_event_team VARCHAR(3),
    last_event_x_cord_adjusted FLOAT,
    last_event_y_cord_adjusted FLOAT,
    distance_from_last_event FLOAT,
    speed_from_last_event FLOAT,
    time_since_last_event FLOAT,
    time_since_faceoff FLOAT,
    player_position_that_did_event VARCHAR(2),
    shooter_time_on_ice FLOAT,
    shooter_time_on_ice_since_faceoff FLOAT,
    time_difference_since_change FLOAT,
    average_rest_difference FLOAT,
    PRIMARY KEY (shot_id),
    FOREIGN KEY (game_id) REFERENCES game(game_id),
    FOREIGN KEY (team_code) REFERENCES team(team_code),
    FOREIGN KEY (shooter_player_id) REFERENCES player(player_id),
    FOREIGN KEY (goalie_id) REFERENCES player(player_id)
);